flat_install_packages_if_needed_and_load.Rmd:
  path: dev/flat_install_packages_if_needed_and_load.Rmd
  state: active
  R:
  - R/install_packages_if_needed_and_load.R
  - R/pkg_test_internal_functions.R
  tests:
  - tests/testthat/test-install_packages_if_needed_and_load.R
  - tests/testthat/test-pkg_test_internal_functions.R
  vignettes: vignettes/package-install-if-needed-and-load.Rmd
  inflate:
    flat_file: dev/flat_install_packages_if_needed_and_load.Rmd
    vignette_name: package install if needed and load
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
