flat_packages_management.Rmd:
  path: dev/flat_packages_management.Rmd
  state: active
  R:
  - R/install_packages_if_needed_and_load.R
  - R/install_packages_not_installed.R
  - R/load_packages.R
  tests: tests/testthat/test-install_packages_if_needed_and_load.R
  vignettes: vignettes/packages_management.Rmd
  inflate:
    flat_file: dev/flat_packages_management.Rmd
    vignette_name: packages_management
    open_vignette: false
    check: true
    document: true
    overwrite: 'yes'
    clean: true
    codecov: false
