flat_packages_management.Rmd:
  path: dev/flat_packages_management.Rmd
  state: active
  R: R/install_packages_if_needed_and_load.R
  tests: tests/testthat/test-install_packages_if_needed_and_load.R
  vignettes: []
  inflate:
    flat_file: dev/flat_packages_management.Rmd
    vignette_name: .na
    open_vignette: false
    check: true
    document: true
    overwrite: 'yes'
    clean: true
    codecov: false
