# WARNING - Generated by {fusen} from dev/flat_install_packages_if_needed_and_load.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("pkg_test_internal_functions works", {
  expect_true(inherits(pkg_test_internal_functions, "function")) 
})
