# WARNING - Generated by {fusen} from dev/flat_install_packages_if_needed_and_load.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("install_packages_if_needed_and_load works", {
  expect_true(inherits(install_packages_if_needed_and_load, "function")) 
})
