# WARNING - Generated by {fusen} from dev/flat_packages_management.Rmd: do not edit by hand # nolint: line_length_linter.

#' Install packages not installed if needed
#'
#' Install all the packages which are not installed.
#' 
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#' @return nothing
#' 
#' @noRd
#' @keywords internal
install_packages_not_installed <- function(pkgs) {
  
  pkgs_not_installed <- 
    pkgs[!(pkgs %in% rownames(installed.packages()))]
  install.packages(pkgs_not_installed,
                   repos = "https://mirror.ibcp.fr/pub/CRAN/")

}
