# WARNING - Generated by {fusen} from dev/flat_install_packages_if_needed_and_load.Rmd: do not edit by hand # nolint: line_length_linter.


#' Install package if needed and load
#' 
#' Install all the non installed packages among a vector of package names
#' and load them all.
#' 
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#' @importFrom utils install.packages installed.packages
#' @returns nothing
#' 
#' @export
#'
#'
#' @examples
#' install_packages_if_needed_and_load(c("rlang", "lobstr"))

install_packages_if_needed_and_load <- function(pkgs) {
  
  install_packages_not_installed(pkgs)
  load_packages(pkgs)
  
}

#' Install packages not installed if needed
#'
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#'
#' @returns nothing
#' @noRd
#' @keywords internal
install_packages_not_installed <- function(pkgs) {

  pkgs_not_installed <- 
    pkgs[!(pkgs %in% rownames(installed.packages()))]
  install.packages(pkgs_not_installed,
                   repos = "https://mirror.ibcp.fr/pub/CRAN/")

}

#' Load packages
#' 
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#'
#' @returns nothing
#' @noRd
#' @keywords internal
load_packages <- function(pkgs) {

  invisible(lapply(pkgs, FUN = library, character.only = TRUE))

}

