# WARNING - Generated by {fusen} from dev/flat_packages_management.Rmd: do not edit by hand # nolint: line_length_linter.


#' Install package if needed and load
#' 
#' Install all the non installed packages among a vector of package names
#' and load them all.
#' 
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#' @importFrom utils install.packages installed.packages
#' @return nothing
#' 
#' @export
#'
#' @examples
#' install_packages_if_needed_and_load(c("rlang", "lobstr"))
install_packages_if_needed_and_load <- function(pkgs) {
  
  install_packages_not_installed(pkgs)
  load_packages(pkgs)
  
}

