# WARNING - Generated by {fusen} from dev/flat_packages_management.Rmd: do not edit by hand # nolint: line_length_linter.

#' Load packages
#' 
#' Load all the packages
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#' 
#' @return nothing
#' @noRd
#' @keywords internal
load_packages <- function(pkgs) {

  invisible(lapply(pkgs, FUN = library, character.only = TRUE))

}
