# WARNING - Generated by {fusen} from dev/flat_packages_management.Rmd: do not edit by hand # nolint: line_length_linter.

#' Test d'usage des fonctions internes
#' 
#' Teste l'usage des fonctions internes définies dans le chunk de définition de la fonction install_packages_if_needed and load
#' 
#' @param pkgs character vector of the names of packages whose current versions should be downloaded from the repositories.
#'
#' @return nothing
#' 
#' @export
#' 
#' @examples
#' pkg_test_internal_functions("lobstr")
pkg_test_internal_functions <- function(pkgs){
    load_packages(pkgs)
}
